COMPONENT=BSCTPTestAppC

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
          -DTOSH_DATA_LENGTH=35 \
          -DCC2420_DEF_RFPOWER=31

include $(MAKERULES)

